### PR TITLE
chore: Add views for permissions table

### PR DESCRIPTION
**Pull request by suyash-naithani**
This PR has the following changes:
- Add view for the permissions table
- Integrate permissions table
- Integrate permissions modal

Checklist of items to test and are included in thePR
https://docs.google.com/document/d/1umA-Vzme95mNDd5C9rap7qfjRe9pxA2vXhVAES4z8Xc/edit

### CODE REVIEW

**Comment by suyash-naithani** [comment]
@riccardo-forina 
aclRefetch
 I've made some changes to the acls, let me know what you think. In the gif above, I've outlined a bug I can't seem to fix. If we delete a permission and stay on the page for long enough, the acls will eventually come back on data refetching as the acl is not really deleted until we click save. I tried to increase the stale time, set keepPreviousData to false but that didn't work. I've finished off on the rest of the stuff but need to fix this bug. Any tips on how I can fix this?
 
 This document outlines the checklist for the acls PR
 https://docs.google.com/document/d/1umA-Vzme95mNDd5C9rap7qfjRe9pxA2vXhVAES4z8Xc/edit

**Comment by riccardo-forina** [comment]
You should work on a copy of the object you get the first time the dialog opens. That's the one that can be mutated and sent back for saving. The correct thing to do is while receiving the latest version of the data, check if it changed somewhere and if so, notify the user that there is newer data and ask if he wants to discard any change and start again with the new data, or keep going.

**Comment by suyash-naithani** [comment]
Thanks @riccardo-forina I have made some changes and it works as expected. Please review the changes and let me know anything that needs to be addressed

**Review by anukritijha — CHANGES_REQUESTED** [review]
Found a few issues while testing this:

- In edit permissions for user Accounts, the user Account name should be shown in the text in Assiign Permission section.
- The existing Permissions are not shown correctly, if a permission is added for a specific SA, the change gets reflected to to all the accounts.

**Comment by anukritijha** [comment]
@suyash-naithani Found another issue:
> A user is able to add permission to their own account in another user's instance. Expectation is that the user should not be allowed to select their own account if they are managing another user's instance.

**Comment by hemahg** [comment]
I tested the Acls permission for the create topic, everything works as expected.

**Comment by anukritijha** [comment]
Screenshot 2023-02-21 at 8 03 30 PM

We should show descriptive messages when there is an error.

**Review by anukritijha — APPROVED** [review]

**Review by hemahg — APPROVED** [review]
LGTM

**Pull request merged**
